# Copyright © 2024 Advanced Micro Devices, Inc. All rights reserved.

repos:
  # Python hooks
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
  # C++ hooks
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        types_or: [c++, c, proto]
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    - id: cmake-format
      args: [
        -c, ci/.cmake-format.json,
        --in-place,
      ]
  # general hooks
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
      - id: markdown-link-check
        args: [-q, -c, ci/link_check.json]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=15000']
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
exclude: '(ext/.*|third_party/.*)'
